name: AI Trouble Shooter CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # ---------- Docker Hub Login ----------
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # ---------- Build & Push FastAPI ----------
    - name: Build & Push FastAPI
      run: |
        docker build -t g3anu/fastapi-app:latest ./app
        docker push g3anu/fastapi-app:latest

    # ---------- Build & Push UI ----------
    - name: Build & Push UI
      run: |
        docker build -t g3anu/ui:latest ./ui
        docker push g3anu/ui:latest

    # ---------- Copy docker-compose.yml ----------
    - name: Copy docker-compose.yml to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_KEY }}
        source: "docker-compose.yml"
        target: "/home/${{ secrets.EC2_USERNAME }}/deploy"

    # ---------- Deploy ----------
    - name: Deploy on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ~/deploy

          
          docker-compose down
          docker-compose pull
          docker-compose up -d